### ISSUE TITLE
Codec cant encode character

### ISSUE THREAD

**Issue by TheBull963** [kevthehermit/PasteHunter#1]
I have been trying to get the script to pull in pastes for a couple of days. I havent had the script import any records as of yet, I keep getting the following error:
Traceback (most recent call last):
  File "pastehunter.py", line 95, in <module>
    matches = rules.match(data=raw_paste_data)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 62: ordinal not in range(128)

Please let me know if there is any other information you need as this is the first time I am putting in an issue.

**Comment by kevthehermit** [comment]
I will add some error handling to the script later today, that will hopefully identify the paste that's causing this to break.

**Comment by kevthehermit** [comment]
I have not seen this error before. I have pushed a new version that contains some error handling. If you can try again and if it keeps breaking let me know the pasteid and i will have a look.

**Comment by coolacid** [comment]
Are you using Python3? Python 2 didn't do encoding very well, however Python3 works just fine.

**Comment by kevthehermit** [comment]
Updated the read me to specify this uses python 3. 
Closing. @TheBull963 If you still have issues please re open.
