### ISSUE TITLE
improving base64.yar rule

### ISSUE THREAD

**Issue by FafnerKeyZee** [kevthehermit/PasteHunter#10]
Hey, 

I think it should be better to have

```
    condition:
$b64_exe at 0

```
instead of : 

```
    condition:
$b64_exe
```

**Comment by kevthehermit** [comment]
It was originally at 0 the same as the other base64. However I was finding a lot of base64 exe files inside powershell scripts, VB scripts etc. So the at 0 was missing these

**Comment by FafnerKeyZee** [comment]
Ok, I understand better :)
