### ISSUE TITLE
Custom Yara Rules

### ISSUE THREAD

**Issue by ahezza** [kevthehermit/PasteHunter#103]
I've noticed you've updated the YaraRule part of the settings.json and the index.yar is now missing from .../pastehunter/YaraRules:

```
  "yara": {
    "default_rules": true,
    "custom_rules": "none",
    "exclude_rules": [],
    "blacklist": true,
    "test_rules": false
```

I checked the readthedocs and noticed this section hasn't been updated. 
How do you add your own Yara Rules on the last version?

**Comment by Plazmaz** [comment]
Good catch on the out of date docs. To add custom rules simply change "none" to point to your custom rules file.

**Comment by ahezza** [comment]
Thanks for your prompt response.

Can you have more than 1 custom rules file?

**Comment by ahezza** [comment]
@Plazmaz I also get the following error when trying to run the latest version too:

`Jan 20 16:31:18 [omitted] python3[12455]: ERROR:common.py:Unable to read config file '~/.config/pastehunter.json'`

Is this line correct in the pastehunter-cli file?

**Comment by Plazmaz** [comment]
1. Yes, you can have more than one custom rule file by using yara's "include" keyword in your main custom rules file (this is what the index.yar did)
2. Your config.json is now going to need to be ~/. config/pastehunter.json.

**Comment by ahezza** [comment]
Many thanks, I've got it up and running :)
