### ISSUE TITLE
Installation documentation should state dependencies

### ISSUE THREAD

**Issue by Land3r** [kevthehermit/PasteHunter#105]
Hello

I stumbled across some issues while installing PasteHunter using pip, because of missing packages on my system (Debian 9).

I had to install build-essential package using apt-get (for gcc) and wheel using pip.

It isn't really a bug, but maybe the dependencies that the setup.py script is build upon should be listed in https://github.com/kevthehermit/PasteHunter/blob/master/docs/installation.rst ?

What do you think ?

I can add an appendix to the installation documentation if you feel that this is relevant

Regards,
Nicolas

**Comment by Plazmaz** [comment]
Hey, thanks for the feedback. Are there any other dependencies you noticed were missing?

**Comment by Land3r** [comment]
No, after installing gcc and wheel with pip, the process of installing PasteHunter with pip went through and i am able tu run it correctly :)
