### ISSUE TITLE
starting pastehunter : pastehunter.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by DannyCork** [kevthehermit/PasteHunter#106]
Forgive me if this if obvious....

I'm following the instructions for a local install from git https://pastehunter.readthedocs.io/en/latest/installation.html

```
Starting
You can run pastehunter by calling the script by name.

python3 pastehunter.py
```

I've done  

- git clone
- sudo pip3 install -r requirements.txt
- downloaded, built and installed yara
- created a copy of settings.json

Upon executing python3 pastehunter.py I get :

```
$python3 pastehunter.py
python3: can't open file 'pastehunter.py': [Errno 2] No such file or directory
```

This is correct as there is no pastehunter.py anywhere. Am I missing something obvious? Thanks in advance.

**Comment by Plazmaz** [comment]
try `./pastehunter-cli`?

**Comment by Plazmaz** [comment]
I've updated the docs in 5b65377b4149dd2938f3e9829bc85abfd4f4ffc0 to be clearer, closing this out.
