### ISSUE TITLE
rules = yara.compile(filepaths=rule_files, externals={'filename': ''}) yara.SyntaxError: /usr/local/lib/python3.6/dist-packages/pastehunter/YaraRules/index.yar(8): can't open include file: custom_keywords.yar

### ISSUE THREAD

**Issue by smetal1** [kevthehermit/PasteHunter#108]
Getting the following issue while running the cli:

rules = yara.compile(filepaths=rule_files, externals={'filename': ''})
yara.SyntaxError: /usr/local/lib/python3.6/dist-packages/pastehunter/YaraRules/index.yar(8): can't open include file: custom_keywords.yar

**Comment by Plazmaz** [comment]
Can you make sure `custom_rules` is set to `"none"` in your config.json file please?
