### ISSUE TITLE
rules.match returns strings instead of dict

### ISSUE THREAD

**Issue by matse144** [kevthehermit/PasteHunter#11]
I'm running pastehunter with python 3.5.2 on ubuntu and yara 3.4.
As soon as I get a hit and it tries to parse it I get 

Traceback (most recent call last):
  File "pastehunter.py", line 125, in <module>
    if match.rule == 'core_keywords' or match.rule == 'custom_keywords':
AttributeError: 'str' object has no attribute 'rule'

I checked the dict rules.match returns and it seems that it only has one subelement called main which then includes all the elements the filter looks for in a list. 
Any idea what I could change?

Many thanks,
Mat

**Comment by kevthehermit** [comment]
This is usually because your version of yara or python-yara is too old. 

Can you check your versions please and make sure they match

```
thehermit@pastehunter:~$ python3
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import yara
>>> yara.__version__
'3.6.3'
>>> 
thehermit@pastehunter:~$ yara -v
3.6.3
```

**Comment by matse144** [comment]
Great thanks, I manually installed yara 3.7 and python-yara 3.7 and now it works.
