### ISSUE TITLE
docker-compose settings.json location

### ISSUE THREAD

**Issue by dmille6** [kevthehermit/PasteHunter#111]
i've been using pastehunter for years.. new version is throwing me off. 
i'd like to use docker/docker-compose to run it. 
when i do a "docker-compose up"
i get this error:

# error 
pastehunter      | INFO:pastehunter-cli:Starting PasteHunter Version: 1.0
pastehunter      | INFO:pastehunter-cli:Reading Configs
pastehunter      | ERROR:common.py:Unable to read config file '~/.config/pastehunter.json'

i've created that folder under my users account and the root.. no luck at all.. 
i've tried volume bind mounting to a settings.json i have in the docker compose:
## in the docker compose:

 .. still no luck..   
pastehunter:
    build: .
    container_name: pastehunter
    volumes:
      - ./logs:/usr/src/pastehunter/logs
      - /usr/src/pastehunter/settings.json:/opt/Pastehunter/settings.json

any suggestions would be appreciated

**Comment by mr-satan1** [comment]
I'm in the same boat as you.

**Comment by Plazmaz** [comment]
Was able to reproduce, should be resolved in the latest version of the master branch. May be a while before I cut a release, have been pretty busy with other things recently.
