### ISSUE TITLE
Q&A - Slexy  - URL open error certificate verify failed

### ISSUE THREAD

**Issue by dmorgan07** [kevthehermit/PasteHunter#115]
Hello, I'm trying to make use of the tool for the first time and I'm getting an error with the input site 'slexy' as it complains  
ERROR: Unable to fetch list from inputs.slexy : <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED]> certificate verify failed. I'm quite a beginner and could someone help me with fixing the issue or if there are any workarounds. Thanks in advance

**Comment by Plazmaz** [comment]
Interesting, can you provide some more information?

1. What OS are you running on?
2. Have you changed anything in the configuration? If so, what have you changed?
3. Is that the full output of the error, or is there additional information provided?

**Comment by dmorgan07** [comment]
Thanks for the response plazmaz. I'm currently running pastehunter on a Ubuntu 18.04 VM and I all I changed in the config file was to include all pastes irrespective of a rule match and I changed the output from elastic to json.

Below is the error I got while running it today:

ERROR:pastehunter-cli:Unable to fetch list from pastehunter.inputs.slexy: HTTPSConnectionPool(host='slexy.org', port=443): Max retries exceeded with url: /recent (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))

Pastebin works fine but I'm getting this issue with slexy.

**Comment by Plazmaz** [comment]
Are you able to access slexy.org via curl?
```
curl https://slexy.org
```

**Comment by dmorgan07** [comment]
I just noticed I could not access the site using curl. I get the below error

curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

Any reason why it is the case?

**Comment by Plazmaz** [comment]
It sounds like you need to update your root CA bundle. This does not appear to be an issue with pastehunter. Going to close this.
