### ISSUE TITLE
Yara error - input in flex scanner failer.

### ISSUE THREAD

**Issue by lotr1** [kevthehermit/PasteHunter#119]
Running pastehunter from python venv. 
pastehunter 1.4.0
yara  4.0.2

The error I get is:

INFO:pastehunter-cli:Adding custom rules from logs
ERROR:pastehunter-cli:Unable to Create Yara index: /home/ee-user/.config/yara/logs(1): input in flex scanner failed
Traceback (most recent call last):
  File "/home/ee-user/VE/PasteHunter/bin/pastehunter-cli", line 382, in main
    rules = yara.compile(filepaths=rule_files, externals={'filename': ''})
yara.SyntaxError: /home/ee-user/.config/yara/logs(1): input in flex scanner failed

Issue is caused by logs being generated in the yara folder. By disabling logs the issue is resolved.
rather unsure why the logs are generated in the yara folder.

**Comment by Plazmaz** [comment]
Can you provide your settings.json (with keys removed) and a list of files in /home/ee-user/.config/yara/logs please?

**Comment by lotr1** [comment]
Issue is resolved in latest release. Thank you. Nice work.

**Comment by Plazmaz** [comment]
Happy to hear it.
