### ISSUE TITLE
No module named 'inputs'

### ISSUE THREAD

**Issue by lotr1** [kevthehermit/PasteHunter#120]
Running pastehunter from python venv. 
pastehunter 1.4.0
yara  4.0.2

The error I get is:

ERROR:pastehunter-cli:Unable to fetch list from pastehunter.inputs.pastebin: No module named 'inputs'

Issue is present in all versions except version 1.0

**Comment by Plazmaz** [comment]
Resolved by #118, haven't cut a new release yet.

**Comment by Plazmaz** [comment]
1.4.1 should be out with a fix for this within an hour or so.
