### ISSUE TITLE
Issue regarding pastehunter or possibly pastebin API

### ISSUE THREAD

**Issue by lotr1** [kevthehermit/PasteHunter#122]
I am testing pastehunter and as a control measure I am posting on pastebin to see if we catch the paste. In 5 out of 5 trials we have missed it, using a simple string such as test67809 for example.
Could there be any explanation as to why this is happening?

**Comment by Plazmaz** [comment]
Unfortunately this is almost certainly Pastebin(you can double check with older versions of PasteHunter if you want to be positive). They've been making changes to their scraping API that have severely damaged our ability to scrape. You can see the full context here #112. I've reached out to them about the issue described in #116, but have gotten no response. You can reach out to them directly if you want to attempt to resolve this, but we have not had much luck with it so far.
