### ISSUE TITLE
Issue with slexy module - timeout

### ISSUE THREAD

**Issue by lotr1** [kevthehermit/PasteHunter#124]
There is an issue when enabling the slexy module:

Unable to fetch list from pastehunter.inputs.slexy: HTTPSConnectionPool(host='slexy.org', port=443): Max retries exceeded with url: /recent (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f274138e9e8>, 'Connection to slexy.org timed out. (connect timeout=15)'))

Rather unsure if this is caused by the API or some other issue. Any help appreciated.

**Comment by Plazmaz** [comment]
Oh sorry! I realized I made the commit but never circled back to you on this. This should be resolved. If you need, you can up the timeout in the latest version as part of the change made here: https://github.com/kevthehermit/PasteHunter/commit/89018f090f0f04ab4046736faa26e9c8091ce809
