### ISSUE TITLE
Can older GitHub and Gist posts be found?

### ISSUE THREAD

**Issue by Phyxioss** [kevthehermit/PasteHunter#128]
Thank you very much for the early answer to the question I asked before. As I mentioned in the title, is it possible to find older posts? For example, 1 week ago or 1 month ago. Is there a setting for this?

Thank you in advance, I wish you healthy days.

**Comment by Plazmaz** [comment]
Ah, no, sorry. Sadly, the amount of data github returns daily is huge. There are some projects dedicated to archiving GitHub's feed like this one:   https://www.gharchive.org/  
You can also use tools for utilizing github search. Our github checks are derived from   https://github.com/techgaun/github-dorks
