### ISSUE TITLE
Rules object has no Attribute 'Save'

### ISSUE THREAD

**Issue by azurism** [kevthehermit/PasteHunter#129]
Running a clean install on a freshly staged Ubuntu box. Any clue why its throwing this error? I compiled yara from source. Running on Ubuntu 20.04. 

root@localhost:~/yara# pastehunter-cli
INFO:pastehunter-cli:Starting PasteHunter Version: 1.4.0
INFO:pastehunter-cli:Reading Configs
INFO:pastehunter-cli:Logging to file disabled.
INFO:pastehunter-cli:Setting Log Level to 20
INFO:pastehunter-cli:Configure Inputs
INFO:pastehunter-cli:Enabled Input: pastebin
INFO:pastehunter-cli:Enabled Input: gists
INFO:pastehunter-cli:Configure Outputs
INFO:pastehunter-cli:Enabled Output: elastic_output
INFO:pastehunter-cli:Compile Yara Rules
INFO:pastehunter-cli:Adding rules from api_keys.yar
INFO:pastehunter-cli:Adding rules from CryptoExchangeApi.yar
INFO:pastehunter-cli:Adding rules from base64.yar
INFO:pastehunter-cli:Adding rules from email_filter.yar
INFO:pastehunter-cli:Adding rules from powershell.yar
INFO:pastehunter-cli:Adding rules from hak5.yar
INFO:pastehunter-cli:Adding rules from password_leak.yar
INFO:pastehunter-cli:Adding rules from core_keywords.yar
INFO:pastehunter-cli:Enable Blacklist Rules
INFO:pastehunter-cli:Adding rules from blacklist.yar
INFO:pastehunter-cli:Adding rules from aws.yar
INFO:pastehunter-cli:Adding rules from database.yar
INFO:pastehunter-cli:Adding rules from general.yar
INFO:pastehunter-cli:Adding rules from certificates.yar
ERROR:pastehunter-cli:Unable to Create Yara index: 'Rules' object has no attribute 'save'
Traceback (most recent call last):
  File "/usr/local/bin/pastehunter-cli", line 386, in main
    rules.save(file=rules_buff)
AttributeError: 'Rules' object has no attribute 'save'

**Comment by Plazmaz** [comment]
What version of yara did you compile, and did you also install yara-python? https://github.com/VirusTotal/yara-python If so, what version?

**Comment by Plazmaz** [comment]
Going to close this pending more info
