### ISSUE TITLE
Rules match will not trigger email alert

### ISSUE THREAD

**Issue by kcompres** [kevthehermit/PasteHunter#17]
The settings for email triggering under the settings.json file are enabled, however the program will not initialize the email triggering.

**Comment by cucx** [comment]
I also have the same issue, is there a way to enable debug for the SMTP post part? i already enabled
```
logging.basicConfig(format='%(levelname)s:%(filename)s:%(message)s', level=logging.DEBUG)
logging.getLogger('requests').setLevel(logging.DEBUG)
```
but that didn't give me anything to go on
thanks!

**Comment by kevthehermit** [comment]
I just tested this and it seems to be working fine. 

My output shows INFO:smtp_output.py: Email Sent
I have the email in my inbox with a copy of the raw json from the paste. 

My Json section looks like this

```
    "smtp_output": {
      "enabled": true,
      "module": "outputs.smtp_output",
      "classname": "SMTPOutput",
      "smtp_host": "mail.techanarchy.net",
      "smtp_port": 587,
      "smtp_tls": true,
      "smtp_user": "mysmtpusername@domainname.com",
      "smtp_pass": "supersekrtipassword",
      "recipient": "mygmailaccount@gmail.com",
      "rule_list": ["custom_keywords"]
    }
```

**Comment by kevthehermit** [comment]
Unable to replicate so closing.
