### ISSUE TITLE
AttributeError: 'str' object has no attribute 'rule'

### ISSUE THREAD

**Issue by p0x** [kevthehermit/PasteHunter#2]
**I tried to run the script after setup all the requirement but there is an error before sending the results to Elasticsearch** :

Traceback (most recent call last):
  File "pastehunter.py", line 100, in <module>
    if match.rule == 'core_keywords' or match.rule == 'custom_keywords':
AttributeError: 'str' object has no attribute 'rule'

I used **python3**.

**Comment by kevthehermit** [comment]
Which version of yara are you using? Did you build from source or did you install via your distro like apt?
distro versions are out of date. You need to be using a 3x version of yara with the 3x python bindings.

**Comment by p0x** [comment]
I'm using YARA 3.6.3 and Python 3.5.2, Yara built from source

**Comment by p0x** [comment]
I have fixed the issue by the following commands:

$ git clone --recursive https://github.com/VirusTotal/yara-python
$ cd yara-python
$ python3 setup.py build
$ sudo python3 setup.py install

**Comment by kevthehermit** [comment]
Glad to see you have fixed will mark this as closed and add some notes to the readme about checking versions.

**Comment by azurism** [comment]
I'm seeing the same issue. Any idea what's up? 

I've tried Pastehunter 1.0 and 1.1. 
I'm using Python 3.7 and Yara 3.11.

**Comment by Plazmaz** [comment]
@azurism can you please give your stack trace in a new issue? It wouldn't be the same line numbers for sure, a good amount of the code has changed since this was opened.
