### ISSUE TITLE
typo in settings.json.sample

### ISSUE THREAD

**Issue by FafnerKeyZee** [kevthehermit/PasteHunter#23]
In settings.json.sample, there is a typo for output_path :

"csv_output": {
      "enabled": false,
      "module": "outputs.csv_output",
      "classname": "CSVOutput",
      "output_path": "/logs/csv/"
},

Should be:
    "csv_output": {
      "enabled": false,
      "module": "outputs.csv_output",
      "classname": "CSVOutput",
      "output_path": "logs/csv/"
},

**Comment by kevthehermit** [comment]
Thanks Fixed
