### ISSUE TITLE
pastebin.py:Unable to parse paste results: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by Thestorm77** [kevthehermit/PasteHunter#26]
when running pastehunter.py i get the following error on the script for pastepin.py 

pastebin.py:Unable to parse paste results: Expecting value: line 1 column 1 (char 0)

Any ideas how to solve this?

**Comment by kevthehermit** [comment]
Sounds like your getting an error from the API. Did you whitelist your IP address on pastebin

**Comment by Thestorm77** [comment]
Pecisely it. My IP address changed, which it rarely does. Need to make sure i remember that next time. Thanks for your quick reply
