### ISSUE TITLE
paste.ee

### ISSUE THREAD

**Issue by gquere** [kevthehermit/PasteHunter#28]
It's mentioned in the README that you plan to support paste.ee as well. Are you sure their API supports this? I tried it myself and it doesn't seem to work because as I understand it you can only list your own pastes using a user application key (https://pastee.github.io/docs/#pastes). I'll be happy to help implement the feature if you've found another way.

**Comment by kevthehermit** [comment]
I have removed paste.ee from the list of ToDo, as you said there is no way to reliably get a list of recent pastes.
