### ISSUE TITLE
I'm missing something

### ISSUE THREAD

**Issue by xitiu** [kevthehermit/PasteHunter#3]
I'm trying to make it work, but I'm missing something in instructions. I've made all steps till the cron script.
http://storage1.static.itmages.com/i/17/0914/h_1505422329_9821783_a362db27be.png
The message is that the file or directory was not found.

**Comment by p0x** [comment]
try this command 

echo "*/2 * * * *   xix cd /home/xix/pastehunter && python3 pastabean.py >> /home/xix/pastehunter/cronlog.txt" > /etc/cron.d/pastehunter

then : 
ls -la /etc/cron.d/pastehunter

**Comment by xitiu** [comment]
Thanks p0x, worked!

**Comment by kevthehermit** [comment]
Fixed the name of the script in the cronjob example. It was using an old name for the script.
