### ISSUE TITLE
Blacklisted pastebin.com paste

### ISSUE THREAD

**Issue by Thestorm77** [kevthehermit/PasteHunter#30]
Recently i started receiving these errors. I have not made any configuration changes and my IP is currently whitelisted in pastebin. Any ideas how to solve it?

**Comment by kevthehermit** [comment]
There is a blacklist in the config file that's enabled by default. There are done rules to prevent some spammy pastes. You can turn this off in the JSON config

**Comment by Thestorm77** [comment]
Great. Thanks
