### ISSUE TITLE
Should update the Pastebin API URL

### ISSUE THREAD

**Issue by L3houx** [kevthehermit/PasteHunter#31]
Pastebin updated the API links. If you don't change it until April 27 you will be unable to use the scraper. Let's take a look at the Pastebin's scraping doc. https://pastebin.com/doc_scraping_api

Use these:
api_scrape : `https://scrape.pastebin.com/api_scraping.php`
api_raw : `https://scrape.pastebin.com/api_scrape_item.php?i=`

Instead of these:
api_scrape : `https://pastebin.com/api_scraping.php`
api_raw : `https://pastebin.com/api_scrape_item.php?i=`

**Comment by kevthehermit** [comment]
Thanks updating now
