### ISSUE TITLE
Installation troubleshooting

### ISSUE THREAD

**Issue by dmzer0** [kevthehermit/PasteHunter#41]
Hi,  I have installed elasticsearch, kibana, python libraries and cloned the package to the box. However when i run python3 pastehunter.py the tool comes back with the following error:

user@ubuntu:~/pastehunter$ python3 pastehunter.py
INFO:pastehunter.py:Starting PasteHunter Version: 0.1
INFO:pastehunter.py:Reading Configs
ERROR:common.py:Unable to parse config file: Expecting ',' delimiter: line 93 column 5 (char 2487)
Traceback (most recent call last):
  File "pastehunter.py", line 38, in <module>
    if "logging_level" in conf["general"]:
TypeError: 'NoneType' object is not subscriptable

I have tried a couple things such as running pastehunter in different versions of python.

Any ideas?

**Comment by kovacsbalu** [comment]
Hi @dmzer0 check #39. You can fix it in your settings.json line 92.

**Comment by dmzer0** [comment]
Thanks that worked. Much appreciated!
