### ISSUE TITLE
Problem working

### ISSUE THREAD

**Issue by gn0sys** [kevthehermit/PasteHunter#45]
/usr/bin/PasteHunter-master# python pastehunter.py
Traceback (most recent call last):
  File "pastehunter.py", line 8, in <module>
    import requests
ImportError: No module named requests

**Comment by gn0sys** [comment]
I have python3 but the python script itself is stored a level up in .../PasteHunter-master
Should I just copy the .py to usr/bin/ ?

**Comment by kovacsbalu** [comment]
Ok, you have python3. Can you please try to run `python3 pastehunter.py`

**Comment by gn0sys** [comment]
root@kali:/usr/bin/PasteHunter-master# python3 pastehunter.py
Traceback (most recent call last):
  File "pastehunter.py", line 5, in <module>
    import yara
ModuleNotFoundError: No module named 'yara'

**Comment by kovacsbalu** [comment]
much better :)
Did you installed all requirement with pip3?

**Comment by gn0sys** [comment]
Yes I made sure pip3 setuptools is installed and apt install python3-pip as well as apt-get install python3-dev and have ran && update alongside it

**Comment by gn0sys** [comment]
I guess I forgot to run `pip3 install -r requirements.txt ` after apt install finished. Now I am getting `root@kali:/usr/bin/PasteHunter-master# python3 pastehunter.py 
INFO:pastehunter.py:Starting PasteHunter Version: 0.1
INFO:pastehunter.py:Reading Configs
ERROR:common.py:Unable to parse config file: Expecting ',' delimiter: line 93 column 5 (char 2483)
Traceback (most recent call last):
  File "pastehunter.py", line 38, in <module>
    if "logging_level" in conf["general"]:
TypeError: 'NoneType' object is not subscriptable`

**Comment by gn0sys** [comment]
Got it working by fixing the config that was missing a ','. Thanks for your assistance! I really appreciate it!
