### ISSUE TITLE
kibana dashboard setup

### ISSUE THREAD

**Issue by mrjuicy-1** [kevthehermit/PasteHunter#5]
an excellent tool. i have installed all the required packages successfully. kibana is running fine on my browser http://127.0.0.1:5601. the same for elasticsearch: http://127.0.01:9200.
when i run the python3 pastehunter.py i am receiving the below output:
Stored: Q62WAHGR
Stored: IZTA70H5K
Saved 2 Pastes
my only problem is how to integrate kibana, and elasticsearch to show the pastes in the kibana dashboard.
currently my kibana dashboard looks like the attached screenshot
![screenshot-20170930184208-1662x634](https://user-images.githubusercontent.com/32416974/31047221-26263cf6-a60f-11e7-8682-ae1d8df48f91.png)

**Comment by olafhartong** [comment]
replace logstash-* by paste-* and you're fine

**Comment by mrjuicy-1** [comment]
That was the missing part. it works!
Thank you
