### ISSUE TITLE
Slexy.org connection refused

### ISSUE THREAD

**Issue by seyfullahkilic** [kevthehermit/PasteHunter#52]
slexy.org banned our server after running the PasteHunter in 5 minutes.

requests.exceptions.ConnectionError: HTTPSConnectionPool(host='slexy.org', port=443): Max retries exceeded with url: /raw/s2ZRogGN7i?token=4dbda20607eee17c502beca6b457699fb64c4d67e5e94f66ec4a2411711ff794&ts=1540807309 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fc60c810550>: Failed to establish a new connection: [Errno 111] Connection refused'))

**Comment by jcngodaddy** [comment]
Saw that as well, ended up having to disable slexy to prevent crashes.  
Need to be able to dial back the frequency of slexy checks, I believe.

**Comment by kevthehermit** [comment]
This is merged now, will need some more testing.
I will also look at per source rate limit in the main parser
