### ISSUE TITLE
dumpz.org no longer has scraping api

### ISSUE THREAD

**Issue by coltbeck76** [kevthehermit/PasteHunter#53]
as per the website:
" /api/recent
GET

List of recently uploaded dumps.

(!) This API method is no longer available."

and in the terminal it shows : ERROR:dumpz.py:Unable to parse paste results: Expecting value: line 1 column 1 (char 0)

**Comment by kevthehermit** [comment]
This has been disabled in the default config file You can disable it in yours and it will be removed in a future update if we can find no other way to access the pastes.
