### ISSUE TITLE
Can I add blacklist rule?

### ISSUE THREAD

**Issue by imfht** [kevthehermit/PasteHunter#57]
Hi:
    The rule always matches loots of following urls.
```
#b64_url
https://gist.githubusercontent.com/lansetiankongFXQ/f7dfc3e0b827c812ebf06a10bae0b961/raw/101ac98fa42d9eb4b27836e122cc81d495e33c21/MyPython_venv_Lib_site-packages_pip-10.0.1-py3.7.egg_pip__vendor_certifi_cacert.pem
 #db_connection
https://gist.githubusercontent.com/mzegar/723a6c16e065684f6751bca7dc8fd782/raw/6b6f9968d7a106931ef315066d0ec156a1823112/SaveTheEnvironmentGameJam2018_venv_Lib_site-packages_pip-10.0.1-py3.7.egg_pip__vendor_urllib3_util_url.py
```
They are python builtin modules. Is there any way to add a negative rule. When matched the negative rule then the file goes into black list and do not send to output module.
Thanks!

**Comment by kevthehermit** [comment]
You can also add items to blacklist.yar and ensure that "blacklist": true, is set to true in the settings.json file
