### ISSUE TITLE
When SSLErrors occur, threads are frozen

### ISSUE THREAD

**Issue by secbug** [kevthehermit/PasteHunter#58]
It seems that sometimes the two requests.get(raw_paste_uri).text calls in pastehunter.py fire SSLErrors and freeze the executing thread. This is fixed by adding some try-catches around them and letting them cleanly fail.

Turning this:
`raw_paste_data = requests.get(raw_paste_uri).text`

Into this:
```
try:
    raw_paste_data = requests.get(raw_paste_uri).text
except requests.exceptions.SSLError as e:
    logger.error("Unable to scan raw paste : {0} - {1}".format(paste_data['pasteid'], e))
    continue
```

There may be a place here for a separate request function in the future.

**Comment by ahezza** [comment]
I made this change but this stopped the script working altogether. It ran successfully but I never got any hits or even blacklisted hits.

Is this to solve the issue where the script stops getting hits after a certain period of time?

**Comment by secbug** [comment]
It's possible that the copy-paste introduced another error which is crashing the thread. Since I reformatted my comment, it may work now. However, you are better off checking with the code change in the pull request as that code is functioning properly in production on our side.

Our issue we had was due to an SSLError thrown at random times while the code is running on a cloud platform. It seems that if there is a quick change to the VM it's running on or to the network inbetween, it throws an SSLError from the connection attempt to Pastebin. This wasn't being handled which killed the thread and zombified the parent process. We didn't have it "stop getting hits", we had it stop processing altogether.

**Comment by secbug** [comment]
@ahezza I concede, you are correct. The code is now catching the error, but it's crashing due to the paste now being on the stack without a set raw_paste or some other issue affecting the parsing thread. It only just hit our production today.

My belief is, like how the pastebin thread died and left the zombie silent process, the parsing thread is now dying while the pastebin thread lives on. This is leaving PasteHunter is the same state as before, but with a thread with working output adding to a forever growing queue rather than a never growing queue with a forever parsing thread.

I'm in the process of increasing the logging ability of PasteHunter to allow for log output to file (without some dodgy output redirecting) so that someone can catch this the next time it arrives.

**Comment by secbug** [comment]
Have you been working on it long? I'm just flushing out the last of a log file setup now.

**Comment by ahezza** [comment]
Seems to be a new issue since adding the Log to file option:

# python3 pastehunter.py 
INFO:pastehunter.py:Starting PasteHunter Version: 0.2
INFO:pastehunter.py:Reading Configs
ERROR:common.py:Unable to parse config file: Expecting property name enclosed in double quotes: line 116 column 3 (char 3159)
Traceback (most recent call last):
  File "pastehunter.py", line 40, in <module>
    if "log" in conf and conf["log"]["log_to_file"]:
TypeError: argument of type 'NoneType' is not iterable
