### ISSUE TITLE
ERROR:pastehunter.py:Unable to scan raw paste 

### ISSUE THREAD

**Issue by icepaule** [kevthehermit/PasteHunter#64]
Hello kev,

first of all let me thank you for creating this great tool.

Could you help me with below error message I'm getting?
That'd be great. Thanks a lot.

Marcus 

**_ERROR:pastehunter.py:Unable to scan raw paste : SVmF9Z9r - could not map file "<data>" into memory_**

**Comment by secbug** [comment]
This is a handled error introduced by my changes. If there is a "SSLError" or any related network error while fetching the raw data content of a paste, it will log the error and blank the paste out.

Is it completely crashing pastehunter? Or is it continuing paste this error?

**Comment by icepaule** [comment]
Hi secbug,

thanks for that quick answer. :-)
Well if this is the handled version of an error, everything is fine. ;-)

No pastehunter is not crashing after the event. I was just in fear that something goes wrong and the data is not reliable, but with your explanation everything is good.

Thanks a lot anyway for that great tool. I'm importing the data into splunk and doing some nice zhings there. Without pastehunter this would have been hard to realise.

Cheers
Marcus
