### ISSUE TITLE
Paste "size" field should be a JSON integer

### ISSUE THREAD

**Issue by secbug** [kevthehermit/PasteHunter#68]
If it's possible with all of the different site formats, the size field sent from pastes or gists should be submitted as an integer so Elastic and other services can use it for calculations.

**Comment by kevthehermit** [comment]
makes sense and should be easy to update

**Comment by kevthehermit** [comment]
Resolved with commit https://github.com/kevthehermit/PasteHunter/commit/da508ab302bc49a75c728821f1e23342c4d658e4
