### ISSUE TITLE
ES Index is Hardcoded

### ISSUE THREAD

**Issue by recrudesce** [kevthehermit/PasteHunter#7]
It doesn't matter what you configure in the settings.conf file, the Elasticsearch index is hardcoded in the `elastic_output.py` file as `paste_test`

https://github.com/kevthehermit/PasteHunter/blob/master/outputs/elastic_output.py#L23

**Comment by kevthehermit** [comment]
Will fix and push shortly

**Comment by recrudesce** [comment]
Thanks Kev, appreciated.  I have another issue - I'll raise that separately :)

**Comment by kevthehermit** [comment]
Took a while to get the develop branch where i wanted it. 
Now resolved
