### ISSUE TITLE
possible issue with elasticsearch

### ISSUE THREAD

**Issue by smokinchili** [kevthehermit/PasteHunter#70]
After setting up the program and running it, I get this error with elasticsearch:

INFO:pastehunter.py:Starting PasteHunter Version: 1.0
INFO:pastehunter.py:Reading Configs
INFO:pastehunter.py:Enabled Log File: logs/pastehunter.log
INFO:pastehunter.py:Setting Log Level to 0
PUT /paste-test-2019-10/paste/npNFcthk [status:406 request:0.429s]
ERROR:pastehunter.py:Unable to store npNFcthk to <outputs.elastic_output.ElasticOutput object at 0x7f0f95c7be80> with error TransportError(406, 'Content-Type header [] is not supported')

I found this article and it looks similar: 
https://github.com/etsy/411/issues/177

Does anyone have a fix for this?

**Comment by kevthehermit** [comment]
Can you give any more info on your setup please.

OS:
ES Version:
Local or remote ES:

Thanks

**Comment by kevthehermit** [comment]
You can also try pip3 install --upgrade elasticsearch 

I have it pinned to a specific version in the requirements.txt I am going to remove the version restrictions.

**Comment by smokinchili** [comment]
OS: Debian 9.8
ES Version: 6.6.1
Local or remote ES: local, set to localhost

After setting the default python to 3 and adding elasticsearch and VSC repos i executed: 

apt-get install python3-pip python3-requests python3-elasticsearch python3-yara automake libtool make gcc flex bison yara libjansson-dev libmagic-dev python3-magic python3-elasticsearch elasticsearch kibana code pylint3


Thanks!!

**Comment by smokinchili** [comment]
Just an update, I tried with the latest version changes from 03/10/2019 and it is still giving me the error.

**Comment by kevthehermit** [comment]
Thanks, I will find some time this weekend to set up a similar env. 

I'm currently running Ubuntu 18.04 ES 6.5.4 and not seeing the same issue.

**Comment by smokinchili** [comment]
After changing my environment to Kubuntu 18.04.2 and elasticsearch 6.6.2 everything worked as expected now, so closing issue. Thanks!!!!
