### ISSUE TITLE
Error 'scrape_url'

### ISSUE THREAD

**Issue by emanuelstravinsky** [kevthehermit/PasteHunter#72]
All working fine(Ubuntu 16.0.4), but keep showing that error right after "Fetching paste list from inputs.gists"

ERROR:pastehunter.py:Unable to store 55599622 to <outputs.csv_output.CSVOutput object at 0x7f279029d208> with error 'scrape_url

What's the issue with it?

**Comment by bsi-lz** [comment]
the error is occuring, when you have csv output active and using stackexchange as input. in stackexchange.py is the paramter 'scrape_url' not set. you can fix it with adding in stackexchange.py the line  "question_data['scrape_url'] = question['link']

**Comment by Plazmaz** [comment]
Thanks for tracking down the issue, @bsi-lz. I ended up setting `scrape_url` to the link of the question, as `scrape_uri` is the full page. Stackoverflow doesn't have a raw endpoint for individual items, and we have a special case for it in the main loop (which grabs paste content), but a few different output types (slack, csv, etc) expected it to be set. This issue should be resolved in the current master branch.
