### ISSUE TITLE
PasteHunter pegs CPU at 100%

### ISSUE THREAD

**Issue by jdsnape** [kevthehermit/PasteHunter#78]
On my system I was finding that pastehunter was pegging my CPU at 100% because the worker processes spent most of their time busy-looping round q.empty()

I've put a simple sleep statement in (PR below) and it now performs much better (and my fans are quieter!)

**Comment by kevthehermit** [comment]
Thanks, I knew the loop wasn't the best option had not spotted CPU usage. 

Will check and merge tonight

**Comment by TheWorkingDeveloper** [comment]
Git pull is a confirmed solution for me.
