### ISSUE TITLE
SSL Elasticsearch

### ISSUE THREAD

**Issue by recrudesce** [kevthehermit/PasteHunter#8]
I found this while working with Amazon's Elasticsearch environment - SSL is required as our deployment does not support 80/tcp or 9200/tcp, only 443/tcp.

I had to edit https://github.com/kevthehermit/PasteHunter/blob/master/outputs/elastic_output.py#L16 to include use_ssl=True

`self.es = Elasticsearch(es_host, port=es_port, http_auth=(es_user,es_pass), use_ssl=True)`

Would it be possible to configure this in the settings.conf file ?  While I understand this might be an edge case, there's probably some others out there than just me that might have the same kind of deployment.

**Comment by kevthehermit** [comment]
Should be easy to add.

**Comment by kevthehermit** [comment]
This is solved now so closing
