### ISSUE TITLE
[Feature] Pastebin link on Email Attachment

### ISSUE THREAD

**Issue by ahezza** [kevthehermit/PasteHunter#80]
Hello,

Instead of just having the name SMTP attachment of the alert being "Alert.json", would it be possible to add the Pastebin resource locator? Maybe in the format "Alert-[URL].json"

For example, the attachment name could be Alert-8sh8js9Q.json

Many Thanks,

**Comment by kevthehermit** [comment]
Great idea, not sure why I didn't do that in the first place. 
Added in https://github.com/kevthehermit/PasteHunter/commit/4c755bf2dc6091387c75e0dc1713d46f842809dc
