### ISSUE TITLE
Premium paste bin required 

### ISSUE THREAD

**Issue by skirankumar** [kevthehermit/PasteHunter#85]
After installing paste hunter and running it. Paste hunter requires a premium account on paste bin to white list our IP for scraping is there any other option available?

**Comment by ChMaFu** [comment]
> Our scraping API is only available for LIFETIME PRO members, and only for those who have their IP whitelisted.

From [here](https://pastebin.com/doc_scraping_api)

Bottom line: I do not think there is any way to avoid the requirement for a Pro PasteBin account if you want to run PasteHunter.

**Comment by Plazmaz** [comment]
This is correct. There's no way around this. Unfortunately, they don't currently seem to be selling these memberships. I would suggest checking on black friday and/or looking at their twitter.
