### ISSUE TITLE
Unable to scan raw paste : external values must be of type integer, float, boolean, or string

### ISSUE THREAD

**Issue by cran1um** [kevthehermit/PasteHunter#91]
attempting to use the current master branch code....
This line seems to be causing problems:
https://github.com/kevthehermit/PasteHunter/blob/master/pastehunter.py#L218
`matches = rules.match(data=raw_paste_data, externals={'filename': paste_data.get('filename')})`

changing it back to
`matches = rules.match(data=raw_paste_data)` as it was before
https://github.com/kevthehermit/PasteHunter/commit/35970ead32cafca3ea42ff481d7233c7468275dd#diff-89a786455794920a3b00d8ef290451db

seems to allow it to work, but I don't understand what was being done to add support for filenames in rules... I think this still needs some work/review

**Comment by Plazmaz** [comment]
Yep, this was due to some code added for github files. I am fairly sure this is a dupe of #89. Can you test if this still occurs after 7219e5c3f4e61c780203cbe81f849144665c9cfc on master?

**Comment by cran1um** [comment]
looks like I was pulling around the same time you were patching.  Latest commit looks like it is resolved.  Thanks!
