### ISSUE TITLE
Hexadecimal Splunk Output

### ISSUE THREAD

**Issue by ahezza** [kevthehermit/PasteHunter#93]
Hello there,
I am configuring the Splunk Output for Pastehunter. 

I am getting the following output type for every single event I'm getting, some random Hex strings.

\x00+\x00	\x00-\x00\x003\x00&\x00$\x00\x00 \xD4 \x92\xBF\xCBUP\x8C\x8D\xC7\\xF6\xF7\xBEO\x9D\xE7\xDB.B\x9B\xDA\xED8\xDC\xFA\xD9=\x00\x00\x84\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00

I have configured a TCP Data Input over a custom port and set the sourcetype as "syslog", the settings.json for Splunk_Output are as follows:

    "splunk_output": {
      "enabled": true,
      "module": "outputs.splunk_output",
      "classname": "SplunkOutput",
      "splunk_host": "127.0.0.1",
      "splunk_port": 9997,
      "splunk_user": "admin",
      "splunk_pass": "**Omitted**",
      "splunk_index": "threat_intel",
      "splunk_sourcetype": "pastehunter",
      "store_raw": true

What am I doing wrong? FYI running Splunk on the same box as Pastehunter.

Thanks,

**Comment by ahezza** [comment]
Any ideas?

**Comment by Plazmaz** [comment]
Hi @ahezza. This is a relatively new feature we've added. We use https://github.com/splunk/splunk-sdk-python for passing data to splunk, so it's likely an issue with your configuration or some nonstandard behavior in their library.

**Comment by ahezza** [comment]
I recently rebuilt Pastehunter and Splunk in my VPS and pointed it to the default management port and I began seeing data in Splunk.
FYI - the data input doesn't need to be set, just use the default management port. I think I overcomplicated it last time I tried...
