### ISSUE TITLE
Support for http://ix.io/

### ISSUE THREAD

**Issue by r00t9** [kevthehermit/PasteHunter#95]
Hello,

Can we add crawler for http://ix.io/

**Comment by Plazmaz** [comment]
Is there a feed or way to find these pastes outside of bruteforcing urls?
(FWIW it seems fairly feasible to bruteforce, given the URLs I'm seeing are 3-4 chars alphanumeric)

**Comment by Plazmaz** [comment]
Looks like there's a list of anonymous pastes here:
http://ix.io/user/
