### ISSUE TITLE
[WIP] Versioning + Releases

### ISSUE THREAD

**Issue by Plazmaz** [kevthehermit/PasteHunter#98]
This should get us to a much better spot with versioning/releases and allow us to test things more thoroughly.

- [x] Set up versioning using existing tags and semver: https://semver.org/
- [x] Set up a changelog
- [ ] Unit tests
- [x] CI Flow (Github Actions?)
- [x] Create setup.py
- [x] Publish pypi package(maybe as CI step for tagged releases?)

@kevthehermit I am looking for feedback on the CI options and pypi account. I'd imagine the pypi account is something you should own, but there may be a way to set up an organization and add me as a contributor. As for CI, there's several options (Travis, Circle, etc), but github actions will probably be the easiest for us.

**Comment by kevthehermit** [comment]
Have pushed some more updates to the versioning branch. 
Creating as a pip package has introduced some breaking changes in the settings file. 

It pip3 installs globally and you can call pastehunter-cli from anywhere and it seems to be running OK. Collecting pastes, scans and writes to my elastic search.

I am still not happy with some of the file paths, there are some relative paths that are going to run in to issues if installed as root and executed as a user.

Things like log file and paste_history.tmp - Probably need a better way of handling this anyway.

**Comment by Plazmaz** [comment]
@kevthehermit `/opt` may be a better option if storing in user folders is something we want to avoid.
